import type { Beer, User, Order } from "./types"

export const mockBeers: Beer[] = [
  {
    id: "1",
    name: "Golden Ale",
    brand: "Craft Brewery Co.",
    type: "Ale",
    abv: 5.2,
    price: 8.99,
    stock: 45,
    description: "A smooth golden ale with hints of citrus and honey",
    imageUrl: "/golden-ale-beer-bottle.jpg",
    isPremiumOnly: false,
  },
  {
    id: "2",
    name: "Dark Stout",
    brand: "Mountain Brewing",
    type: "Stout",
    abv: 6.8,
    price: 10.99,
    stock: 32,
    description: "Rich and creamy stout with notes of coffee and chocolate",
    imageUrl: "/dark-stout-beer-bottle.jpg",
    isPremiumOnly: false,
  },
  {
    id: "3",
    name: "IPA Reserve",
    brand: "Hoppy Hills",
    type: "IPA",
    abv: 7.2,
    price: 12.99,
    stock: 28,
    description: "Bold IPA with tropical fruit flavors and a hoppy finish",
    imageUrl: "/ipa-beer-bottle.jpg",
    isPremiumOnly: true,
  },
  {
    id: "4",
    name: "Wheat Beer",
    brand: "Sunny Valley",
    type: "Wheat",
    abv: 4.5,
    price: 7.99,
    stock: 56,
    description: "Light and refreshing wheat beer perfect for summer",
    imageUrl: "/wheat-beer-bottle.jpg",
    isPremiumOnly: false,
  },
  {
    id: "5",
    name: "Amber Lager",
    brand: "Classic Brews",
    type: "Lager",
    abv: 5.0,
    price: 8.49,
    stock: 41,
    description: "Smooth amber lager with a balanced malt profile",
    imageUrl: "/amber-lager-beer-bottle.jpg",
    isPremiumOnly: false,
  },
  {
    id: "6",
    name: "Belgian Tripel",
    brand: "Monastery Ales",
    type: "Belgian",
    abv: 8.5,
    price: 14.99,
    stock: 18,
    description: "Complex Belgian tripel with spicy and fruity notes",
    imageUrl: "/belgian-tripel-beer-bottle.jpg",
    isPremiumOnly: true,
  },
  {
    id: "7",
    name: "Pilsner Classic",
    brand: "Heritage Brewing",
    type: "Pilsner",
    abv: 4.8,
    price: 7.49,
    stock: 62,
    description: "Crisp and clean pilsner with a refreshing finish",
    imageUrl: "/pilsner-beer-bottle.jpg",
    isPremiumOnly: false,
  },
  {
    id: "8",
    name: "Porter Reserve",
    brand: "Dark Horse Brewery",
    type: "Porter",
    abv: 6.2,
    price: 11.49,
    stock: 25,
    description: "Robust porter with chocolate and caramel undertones",
    imageUrl: "/porter-beer-bottle.jpg",
    isPremiumOnly: true,
  },
]

export const mockUser: User = {
  id: "1",
  email: "customer@example.com",
  name: "John Doe",
  role: "customer",
  isPremium: false,
  createdAt: new Date(),
}

export const mockAdminUser: User = {
  id: "admin1",
  email: "admin@minimart.com",
  name: "Admin User",
  role: "admin",
  isPremium: true,
  createdAt: new Date(),
}

export const mockOrders: Order[] = [
  {
    id: "order1",
    userId: "1",
    items: [
      { beer: mockBeers[0], quantity: 2 },
      { beer: mockBeers[1], quantity: 1 },
    ],
    total: 28.97,
    status: "completed",
    createdAt: new Date("2025-01-05"),
  },
  {
    id: "order2",
    userId: "1",
    items: [{ beer: mockBeers[3], quantity: 3 }],
    total: 23.97,
    status: "completed",
    createdAt: new Date("2025-01-08"),
  },
]
